### ISSUE TITLE
get-site-urls new version

### ISSUE THREAD

**Issue by alex-page** [pattyde/backstop-scenario-generator#4]
Hey I recently update `get-site-urls` and patched some bugs. Let me know if you have any issues!

**Comment by qiigodev** [comment]
I keep getting this block of errors when I run generate-scenarios:
(node:6496) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at GetSiteUrls (/usr/local/lib/node_modules/backstop-scenario-generator/node_modules/get-site-urls/index.js:146:37)
    at generateObject (/usr/local/lib/node_modules/backstop-scenario-generator/index.js:103:21)
    at writeFile (/usr/local/lib/node_modules/backstop-scenario-generator/index.js:119:22)
    at prompt.get (/usr/local/lib/node_modules/backstop-scenario-generator/index.js:142:2)
    at /usr/local/lib/node_modules/backstop-scenario-generator/node_modules/prompt/lib/prompt.js:336:32
    at /usr/local/lib/node_modules/backstop-scenario-generator/node_modules/async/lib/async.js:154:25
    at assembler (/usr/local/lib/node_modules/backstop-scenario-generator/node_modules/prompt/lib/prompt.js:333:9)
    at /usr/local/lib/node_modules/backstop-scenario-generator/node_modules/prompt/lib/prompt.js:342:32
    at /usr/local/lib/node_modules/backstop-scenario-generator/node_modules/prompt/lib/prompt.js:625:5
    at Interface.onLine (/usr/local/lib/node_modules/backstop-scenario-generator/node_modules/read/lib/read.js:111:5)
(node:6496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:6496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


I have tried several different urls with the same result. I am running this on linux command line

**Comment by alex-page** [comment]
What URL are you using? 

This project still needs an update for the `get-site-urls` package which could be causing some issues.
